/** First-release flight, combat and rider defaults, in metres / seconds / radians. */
export const XONGKORO = {
  maxHp: 200,
  cruiseSpeed: 48 / 3.6,
  sprintSpeed: 96 / 3.6,
  minimumSpeed: 7,
  acceleration: 9,
  turnRate: 0.85,
  pitchRate: 0.65,
  maxPitch: 1.1,
  maxBank: 0.65,
  bankResponse: 2.5,
  maxAltitude: 120,
  boundaryMargin: 28,
  takeoffPitch: 0.32,
  landingSpeed: 8,
  landingHeight: 1.5,
  bodyRadius: 1.5,
  bodyHalfLength: 4.7,
  bodyHeight: 2.6,
  torsoHurtSize: [2.7, 2.4, 4.6],
  torsoHurtCenter: [0, 1.4, .7],
  // Reference-frame Head/Jaw weighted surface: .970 × 1.154 × .991 m.
  headHurtSize: [1.1, 1.3, 1.2],
  headHurtSocketOffset: [-.0075, .0759, -.3743],
  wingClearance: 11,
  gravity: 22,
  collisionStep: 0.25,
  attackDamage: 60,
  attackCooldown: 1,
  attackWindup: 0.16,
  attackWindow: 0.2,
  attackRecovery: 0.3,
  attackRadius: 0.65,
  fallLethalHeight: 15,
  aiCruiseHeight: 30,
  aiOrbitRadius: 38,
  aiSeparationRadius: 24,
  aiAttackApproachDistance: 55,
  aiAttackRange: 6.5,
  aiRecoverySeconds: 2.2,
  aiRangedCommitSeconds: 6,
  rangedYawArc: 1.25,
  rangedPitchArc: 1.25,
  aimFreeYaw: 0.45,
  aimFreePitch: 0.32,
  cameraDistance: 20,
  cameraHeight: 1.5,
} as const

/** Pose deltas are applied after the source sample, never accumulated into it. */
export const XONGKORO_VISUAL = {
  lodDistances: [0, 65, 140],
  sprintFlapRate: 1.25,
  attackNeckExtension: .45,
  attackHeadExtension: .25,
  attackNeckPitch: .16,
  attackClawPitch: -.95,
  standingHipPitch: -.12,
  standingKneePitch: .24,
  standingAnklePitch: -.12,
  standingSpread: .10,
  sprintRiderLean: .12,
  groundTransitionSeconds: .38,
  groundBodyPitch: -.35,
  groundThighDirection: [0, -.75, .5],
  groundCalfDirection: [0, -.72, -.62],
  groundAnkleDirection: [0, -1, .24],
  groundFootInfluence: .6,
  flapClearanceStart: .5,
  // Source downstroke reaches 7.46 m below the reference origin.
  flapClearanceFull: 9,
  minimumAudibleFlapWeight: .2,
  maximumAudibleGroundWeight: .8,
} as const
